INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (1, null, 1, 'Mohsin S Barra', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (2, null, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (3, null, 17, 'Brian C Long', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (4, null, 11, 'Francois Bedard', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (5, null, 14, 'Courtney A McKay', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (6, null, 31, 'Breanne L Doyle', 'Money Shots II', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (7, null, 91, 'Benjamin E Pearson', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (8, null, 88, 'Bobby E Feller', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (9, null, 13, 'Timothy D Pettitt', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (10, null, 42, 'John Grass', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (11, null, 33, 'Ed Sanchez', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (12, null, 3, 'Jody Greenberg', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (13, null, 8, 'Gordon L Shyy', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (14, null, 0, 'Patrick W Heil', 'Money Shots II', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (15, null, 83, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (16, null, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (17, null, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (18, null, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (19, null, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (20, null, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (21, null, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (22, null, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (23, null, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (24, null, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (25, null, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (26, null, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (27, null, 8, 'Coryndon H Coles', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (28, null, 65, 'Alexander C Maske', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (29, null, 44, 'Jordan W Dodge', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (30, null, 82, 'Darrin Ng', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (31, null, 6, 'Thomas D Dong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (32, null, 91, 'Gino A Escalante', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (33, null, 31, 'Adam K Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (34, null, 42, 'Kevin J Kalman', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (35, null, 3, 'Luke A Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (36, null, 27, 'Eric  A King', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (37, null, 81, 'Derek W Truesdale', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (38, null, 19, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (39, null, 86, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (40, null, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (41, null, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (42, null, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (43, null, 28, 'James M Lustenader', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (44, null, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (45, null, 51, 'Ian J Balbas', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (46, null, 19, 'Patrick J Mcclenahen', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (47, null, 1, 'Daniel Blumer', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (48, null, 10, 'ELI M MEJIA', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (49, null, 11, 'Chris J Crimi', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (50, null, 22, 'Craig T Nakamura', 'Code Blue', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (51, null, 90, 'Steven J Fazio', 'Code Blue', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (52, null, 7, 'Neeraj Prashar', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (53, null, 6, 'David S Hwang', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (54, null, 12, 'Richard A Shulman', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (55, null, 10, 'David R Kort', 'Code Blue', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (56, null, 27, 'Brian D Toulouse', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (57, null, 8, 'Dave S Kupec', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (58, null, 45, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (59, null, 59, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (60, null, 24, 'Kyle N Chivers', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (61, null, 41, 'Taerim Kim', 'Beerkeepers', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (62, null, 0, 'John W Digiovanni ', 'Beerkeepers', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (63, null, 8, 'Jack Paparian', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (64, null, 19, 'Lyric P Doshi', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (65, null, 15, 'Christine Russell', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (66, null, 2, 'Thomas J Finegan', 'Beerkeepers', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (67, null, 19, 'Brett J Settle', 'Beerkeepers', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (68, null, 21, 'Brandon R Foss', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (69, null, 27, 'Chadrick W Sine', 'Beerkeepers', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (70, null, 12, 'Andrew C Harris', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (71, null, 16, 'William H Tsui', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (72, null, 0, 'Derek S Batoyon', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (73, null, 14, 'Elena   Murphy', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (74, null, 13, 'Razzak G Jallow', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (75, null, 81, 'Michael T Nyland', 'Team America', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (76, null, 24, 'Richard Kapusta', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (77, null, 8, 'Brandon J Realmonte', 'Team America', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (78, null, 8, 'Erich R Klawuhn', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (79, null, 37, 'Kevin J Hutchins', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (80, null, 34, 'Don Labarbera', 'Irish Car Bombs 2', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (81, null, 26, 'Nickolas A Dunn', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (82, null, 20, 'James M Modrall', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (83, null, 70, 'Trevor F Ergas', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (84, null, 56, 'Antrico M Forbes', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (85, null, 25, 'Jonathan R Sebring', 'Irish Car Bombs 2', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (86, null, 15, 'Grant N Gardiner', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (87, null, 45, 'Eric R Sokol', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (88, null, 23, 'Albert Hong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (89, null, 75, 'Robert P Victorino', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (90, null, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (118, 213857, 1, 'Mohsin S Barra', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (119, 213857, 17, 'Brian C Long', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (120, 213857, 11, 'Francois Bedard', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (121, 213857, 14, 'Courtney A McKay', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (122, 213857, 31, 'Breanne L Doyle', 'Money Shots II', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (123, 213857, 91, 'Benjamin E Pearson', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (124, 213857, 88, 'Bobby E Feller', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (125, 213857, 13, 'Timothy D Pettitt', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (126, 213857, 42, 'John Grass', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (127, 213857, 33, 'Ed Sanchez', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (128, 213857, 3, 'Jody Greenberg', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (129, 213857, 8, 'Gordon L Shyy', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (130, 213857, 0, 'Patrick W Heil', 'Money Shots II', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (131, 213857, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (132, 213857, 83, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (133, 213857, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (134, 213857, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (135, 213857, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (136, 213857, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (137, 213857, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (138, 213857, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (139, 213857, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (140, 213857, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (141, 213857, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (142, 213857, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (143, 213857, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (144, 214229, 44, 'Jordan W Dodge', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (145, 214229, 37, 'Kevin J Hutchins', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (146, 214229, 6, 'Thomas D Dong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (147, 214229, 34, 'Don Labarbera', 'Irish Car Bombs 2', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (148, 214229, 26, 'Nickolas A Dunn', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (149, 214229, 20, 'James M Modrall', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (150, 214229, 70, 'Trevor F Ergas', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (151, 214229, 82, 'Darrin Ng', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (152, 214229, 56, 'Antrico M Forbes', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (153, 214229, 25, 'Jonathan R Sebring', 'Irish Car Bombs 2', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (154, 214229, 15, 'Grant N Gardiner', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (155, 214229, 45, 'Eric R Sokol', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (156, 214229, 23, 'Albert Hong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (157, 214229, 75, 'Robert P Victorino', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (158, 214229, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (159, 214229, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (160, 214229, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (161, 214229, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (162, 214229, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (163, 214229, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (164, 214229, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (165, 214229, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (166, 214229, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (167, 214229, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (168, 214229, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (169, 214229, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (170, 214229, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (171, 214229, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (172, 214229, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (173, 213603, 8, 'Coryndon H Coles', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (174, 213603, 65, 'Alexander C Maske', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (175, 213603, 44, 'Jordan W Dodge', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (176, 213603, 82, 'Darrin Ng', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (177, 213603, 6, 'Thomas D Dong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (178, 213603, 91, 'Gino A Escalante', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (179, 213603, 31, 'Adam K Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (180, 213603, 42, 'Kevin J Kalman', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (181, 213603, 3, 'Luke A Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (182, 213603, 27, 'Eric  A King', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (183, 213603, 81, 'Derek W Truesdale', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (184, 213603, 19, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (185, 213603, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (186, 213603, 86, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (187, 213603, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (188, 213603, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (189, 213603, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (190, 213603, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (191, 213603, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (192, 213603, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (193, 213603, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (194, 213603, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (195, 213141, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (196, 213141, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (197, 213141, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (198, 213141, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (199, 213141, 28, 'James M Lustenader', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (200, 213141, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (201, 213141, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (202, 213141, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (203, 213141, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (204, 213141, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (205, 213141, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (206, 213141, 51, 'Ian J Balbas', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (207, 213141, 19, 'Patrick J Mcclenahen', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (208, 213141, 1, 'Daniel Blumer', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (209, 213141, 10, 'ELI M MEJIA', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (210, 213141, 11, 'Chris J Crimi', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (211, 213141, 22, 'Craig T Nakamura', 'Code Blue', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (212, 213141, 90, 'Steven J Fazio', 'Code Blue', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (213, 213141, 7, 'Neeraj Prashar', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (214, 213141, 6, 'David S Hwang', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (215, 213141, 12, 'Richard A Shulman', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (216, 213141, 10, 'David R Kort', 'Code Blue', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (217, 213141, 27, 'Brian D Toulouse', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (218, 213141, 8, 'Dave S Kupec', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (219, 213045, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (220, 213045, 45, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (221, 213045, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (222, 213045, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (223, 213045, 28, 'James M Lustenader', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (224, 213045, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (225, 213045, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (226, 213045, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (227, 213045, 59, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (228, 213045, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (229, 213045, 24, 'Kyle N Chivers', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (230, 213045, 41, 'Taerim Kim', 'Beerkeepers', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (231, 213045, 0, 'John W Digiovanni ', 'Beerkeepers', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (232, 213045, 8, 'Jack Paparian', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (233, 213045, 19, 'Lyric P Doshi', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (234, 213045, 15, 'Christine Russell', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (235, 213045, 2, 'Thomas J Finegan', 'Beerkeepers', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (236, 213045, 19, 'Brett J Settle', 'Beerkeepers', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (237, 213045, 21, 'Brandon R Foss', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (238, 213045, 27, 'Chadrick W Sine', 'Beerkeepers', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (239, 213045, 12, 'Andrew C Harris', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (240, 213045, 16, 'William H Tsui', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (241, 211615, 0, 'Derek S Batoyon', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (242, 211615, 14, 'Elena   Murphy', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (243, 211615, 13, 'Razzak G Jallow', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (244, 211615, 81, 'Michael T Nyland', 'Team America', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (245, 211615, 24, 'Richard Kapusta', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (246, 211615, 8, 'Brandon J Realmonte', 'Team America', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (247, 211615, 8, 'Erich R Klawuhn', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (248, 211615, 19, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (249, 211615, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (250, 211615, 86, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (251, 211615, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (252, 211615, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (253, 211615, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (254, 211615, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (255, 211615, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (256, 211615, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (257, 216166, 22, 'Mickey C Colombo', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (258, 216166, 65, 'Alexander C Maske', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (259, 216166, 3, 'Braden M Connolly', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (260, 216166, 31, 'Adam K Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (261, 216166, 70, 'Trevor F Ergas', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (262, 216166, 84, 'Luke A Scianna', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (263, 216166, 91, 'Gino A Escalante', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (264, 216166, 25, 'Jonathan R Sebring', 'Irish Car Bombs 2', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (265, 216166, 40, 'Karen Fong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (266, 216166, 81, 'Derek W Truesdale', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (267, 216166, 56, 'Antrico M Forbes', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (268, 216166, 67, '<i>Not Signed In</i>', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (269, 216166, 19, 'Cecile Gardiner', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (270, 216166, 55, 'Dylan N Viskochil', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (271, 216166, 34, 'Don Labarbera', 'Irish Car Bombs 2', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (272, 216166, 9, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (273, 216166, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (274, 216166, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (275, 216166, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (276, 216166, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (277, 216166, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (278, 216166, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (279, 216166, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (280, 216166, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (281, 216166, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (282, 204698, 84, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (283, 204698, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (284, 204698, 88, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (285, 204698, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (286, 204698, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (287, 204698, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (288, 204698, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (289, 204698, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (290, 204698, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (291, 204698, 27, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (292, 204698, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (293, 204698, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (294, 204698, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (295, 204698, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (296, 204698, 7, 'Lucas A Brown', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (297, 204698, 1, 'David Greenspan', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (298, 204698, 4, 'Bob Englund', 'The Originals', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (299, 204698, 19, 'Chee Y Hu', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (300, 204698, 11, 'Michael Evans', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (301, 204698, 3, 'Alan J Klapper', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (302, 204698, 71, 'Brant R Fields', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (303, 204698, 44, 'Dennis J Longshore', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (304, 204698, 13, 'Boris Fridlib', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (305, 204698, 77, 'Mark Makiewicz', 'The Originals', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (306, 204698, 68, 'Jon Gire', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (307, 204698, 66, 'Ted S Marks', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (308, 204698, 2, 'Michael A Graves', 'The Originals', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (309, 212309, 22, 'Michael J Appio', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (310, 212309, 14, 'Elena   Murphy', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (311, 212309, 0, 'Derek S Batoyon', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (312, 212309, 81, 'Michael T Nyland', 'Team America', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (313, 212309, 0, 'Daniel A Garaycochea', 'Team America', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (314, 212309, 11, 'Ryan T Omalley', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (315, 212309, 65, 'Patrick R Hazlitt', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (316, 212309, 91, 'Ian A Terra', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (317, 212309, 13, 'Razzak G Jallow', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (318, 212309, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (319, 212309, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (320, 212309, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (321, 212309, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (322, 212309, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (323, 212309, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (324, 212309, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (325, 212309, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (326, 212309, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (327, 212309, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (328, 212309, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (329, 205532, 84, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (330, 205532, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (331, 205532, 88, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (332, 205532, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (333, 205532, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (334, 205532, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (335, 205532, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (336, 205532, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (337, 205532, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (338, 205532, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (339, 205532, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (340, 205532, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (341, 205532, 13, 'Simon P Beckett', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (342, 205532, 42, 'Michael S MacPherson', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (343, 205532, 0, 'Carlos K Delapina', 'K-Wings', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (344, 205532, 7, 'Jani H Maentylae', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (345, 205532, 40, 'Gregory T Fox', 'K-Wings', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (346, 205532, 11, 'Gregory J Moore', 'K-Wings', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (347, 205532, 27, 'Jason S Hesse', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (348, 205532, 14, 'Jeffrey A Wong', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (349, 205532, 68, 'Michael J Hughes', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (350, 205532, 55, 'Andrew W Wu', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (351, 205532, 6, 'MIKE C INGSTER', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (352, 206440, 84, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (353, 206440, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (354, 206440, 88, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (355, 206440, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (356, 206440, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (357, 206440, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (358, 206440, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (359, 206440, 28, '<i>Not Signed In</i>', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (360, 206440, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (361, 206440, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (362, 206440, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (363, 206440, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (364, 206440, 49, '<i>Not Signed In</i>', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (365, 206440, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (366, 206440, 18, 'Christopher R Adams', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (367, 206440, 48, 'Nikolaus A Kriley', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (368, 206440, 10, 'Michael H Arenberg', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (369, 206440, 11, 'Gregory J Moore', 'K-Wings', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (370, 206440, 60, 'Matthew J Burke', 'K-Wings', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (371, 206440, 88, 'Michael T Moore', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (372, 206440, 25, 'Richard E Feldman', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (373, 206440, 62, 'David G Noel', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (374, 206440, 24, 'Benjamin J Hafner', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (375, 206440, 14, 'Jeffrey A Wong', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (376, 206440, 8, 'Erich R Klawuhn', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (377, 206440, 55, 'Andrew W Wu', 'K-Wings', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (378, 207578, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (379, 207578, 42, 'James T Park', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (380, 207578, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (381, 207578, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (382, 207578, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (383, 207578, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (384, 207578, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (385, 207578, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (386, 207578, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (387, 207578, 0, 'Michael J Trojillo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (388, 207578, 19, 'Chad N Okada', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (389, 207578, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (390, 207578, 4, 'Greg Argyle', 'Beerkeepers', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (391, 207578, 41, 'Taerim Kim', 'Beerkeepers', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (392, 207578, 24, 'Kyle N Chivers', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (393, 207578, 8, 'Jack Paparian', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (394, 207578, 80, 'Henry K Chu', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (395, 207578, 39, 'Brandon D Podmayersky', 'Beerkeepers', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (396, 207578, 93, 'Thomas M Connors', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (397, 207578, 15, 'Christine Russell', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (398, 207578, 42, 'James W Fregien', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (399, 207578, 14, 'Allan E Scott', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (400, 207578, 36, 'Kevin A Gladstone', 'Beerkeepers', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (401, 207578, 31, 'Marcin Stylok', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (402, 207578, 3, 'Benjamin Gwin', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (403, 207578, 16, 'William H Tsui', 'Beerkeepers', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (404, 222601, 98, 'Grace C Ding', 'Blade Runners', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (405, 222601, 7, 'Conner T Lee', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (406, 222601, 17, 'Steve A Dippert', 'Blade Runners', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (407, 222601, 31, 'Phillip E Linarte', 'Blade Runners', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (408, 222601, 11, 'Reid O Eggebraaten', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (409, 222601, 42, 'Steven M Pierre', 'Blade Runners', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (410, 222601, 18, 'David L Formenti', 'Blade Runners', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (411, 222601, 1, 'Chase A Piombo', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (412, 222601, 10, 'Raythong C Kono', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (413, 222601, 13, 'Robert J Reese', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (414, 222601, 63, 'Russell J Larsen', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (415, 222601, 91, 'Sean M Wachob', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (416, 222601, 91, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (417, 222601, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (418, 222601, 86, 'Derick R Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (419, 222601, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (420, 222601, 32, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (421, 222601, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (422, 222601, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (423, 222601, 0, 'Michael J Trojillo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (424, 222601, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (425, 222601, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (426, 222601, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (427, 222563, 51, 'Ian J Balbas', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (428, 222563, 19, 'Patrick J Mcclenahen', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (429, 222563, 71, 'Brennan M Bennardo', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (430, 222563, 81, 'Kyle J Mulligan', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (431, 222563, 88, 'Bryan S Goldberg', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (432, 222563, 22, 'Craig T Nakamura', 'Code Blue', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (433, 222563, 18, 'Mark D Hardin', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (434, 222563, 12, 'Richard A Shulman', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (435, 222563, 6, 'David S Hwang', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (436, 222563, 27, 'Brian D Toulouse', 'Code Blue', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (437, 222563, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (438, 222563, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (439, 222563, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (440, 222563, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (441, 222563, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (442, 222563, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (443, 222563, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (444, 222563, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (445, 222563, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (446, 222563, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (447, 208812, 9, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (448, 208812, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (449, 208812, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (450, 208812, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (451, 208812, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (452, 208812, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (453, 208812, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (454, 208812, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (455, 208812, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (456, 208812, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (457, 208812, 0, 'Michael S Chum', 'Pacific Predators', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (458, 208812, 21, 'Jester W Liao', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (459, 208812, 27, 'Daniel   Felnhofer', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (460, 208812, 7, 'Jeremy J Lopopolo', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (461, 208812, 88, 'Andrew A Germond', 'Pacific Predators', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (462, 208812, 80, 'Justin D Lopopolo', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (463, 208812, 18, 'Alexander M Johnson', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (464, 208812, 79, 'David Nguyen', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (465, 208812, 91, 'Andrew M Jones', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (466, 208812, 19, 'Steven L Norwood', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (467, 209365, 19, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (468, 209365, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (469, 209365, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (470, 209365, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (471, 209365, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (472, 209365, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (473, 209365, 28, 'James M Lustenader', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (474, 209365, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (475, 209365, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (476, 209365, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (477, 209365, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (478, 209365, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (479, 209365, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (480, 209365, 19, 'Sandeep   Ashok', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (481, 209365, 19, 'Kyle R Knutson', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (482, 209365, 11, 'Francois Bedard', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (483, 209365, 17, 'Brian C Long', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (484, 209365, 31, 'Breanne L Doyle', 'Money Shots II', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (485, 209365, 91, 'Benjamin E Pearson', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (486, 209365, 3, 'Jody Greenberg', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (487, 209365, 13, 'Timothy D Pettitt', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (488, 209365, 35, 'John F Hauser', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (489, 209365, 81, 'Lisa A Scotch', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (490, 209365, 0, 'Patrick W Heil', 'Money Shots II', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (491, 209365, 2, 'Stephanie Wang', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (492, 209365, 14, 'Raqib H Jones', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (493, 209743, 5, 'Kevin P Chamberlain', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (494, 209743, 19, 'Kyle R Knutson', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (495, 209743, 11, 'Dietmar Ebner', 'Tyrannosaurs', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (496, 209743, 75, 'David J Richardson', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (497, 209743, 0, 'Ray Garcia', 'Tyrannosaurs', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (498, 209743, 18, 'Andrew F Sargent', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (499, 209743, 9, 'Shane S Hajjarian', 'Tyrannosaurs', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (500, 209743, 28, 'Brett J Settle', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (501, 209743, 20, 'Austin Helgeson', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (502, 209743, 13, 'Jon Small', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (503, 209743, 33, 'James Kennedy', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (504, 209743, 45, 'Trevor J Switkowski', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (505, 209743, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (506, 209743, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (507, 209743, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (508, 209743, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (509, 209743, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (510, 209743, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (511, 209743, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (512, 209743, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (513, 209743, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (514, 209743, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (515, 209743, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (516, 209979, 8, 'Coryndon H Coles', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (517, 209979, 42, 'Kevin J Kalman', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (518, 209979, 3, 'Braden M Connolly', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (519, 209979, 34, 'Don Labarbera', 'Irish Car Bombs 2', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (520, 209979, 44, 'Jordan W Dodge', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (521, 209979, 65, 'Alexander C Maske', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (522, 209979, 6, 'Thomas D Dong', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (523, 209979, 1, 'Richard E Mora', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (524, 209979, 26, 'Nickolas A Dunn', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (525, 209979, 82, 'Darrin Ng', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (526, 209979, 7, 'Andrew A Germond', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (527, 209979, 74, 'Zachary S Piper', 'Irish Car Bombs 2', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (528, 209979, 37, 'Kevin J Hutchins', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (529, 209979, 75, 'Robert P Victorino', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (530, 209979, 0, 'Tyler A Jue', 'Irish Car Bombs 2', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (531, 209979, 74, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (532, 209979, 71, 'LEONARDO   PASKIN', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (533, 209979, 37, 'Joseph P Borromeo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (534, 209979, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (535, 209979, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (536, 209979, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (537, 209979, 63, 'Brian T Lindskog', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (538, 209979, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (539, 209979, 19, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (540, 209979, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (541, 211121, 16, 'Brandon M Adriano', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (542, 211121, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (543, 211121, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (544, 211121, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (545, 211121, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (546, 211121, 25, 'Michael J Sprague', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (547, 211121, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (548, 211121, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (549, 211121, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (550, 211121, 0, 'Michael J Trojillo', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (551, 211121, 1, 'William A Robinson', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (552, 211121, 36, 'Olivier J Bernard', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (553, 211121, 13, 'Brian L Luptak', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (554, 211121, 1, 'Jeffrey Burridge', 'Pacific Predators', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (555, 211121, 14, 'Sean  McIntosh', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (556, 211121, 17, 'Benjamin A Cousins', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (557, 211121, 77, 'Kevin L Mitchell', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (558, 211121, 18, 'Alexander M Johnson', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (559, 211121, 12, 'Darrin Ng', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (560, 211121, 91, 'Andrew M Jones', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (561, 211121, 25, 'Jason R Sessler', 'Pacific Predators', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (562, 215346, 5, 'Kevin P Chamberlain', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (563, 215346, 10, 'Nishad   Pai', 'Tyrannosaurs', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (564, 215346, 9, 'Scott Dougall', 'Tyrannosaurs', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (565, 215346, 11, 'Dietmar Ebner', 'Tyrannosaurs', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (566, 215346, 75, 'David J Richardson', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (567, 215346, 1, 'Todd Friedman', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (568, 215346, 70, 'Jorge A Rosas', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (569, 215346, 36, 'Kevin A Gladstone', 'Tyrannosaurs', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (570, 215346, 28, 'Brett J Settle', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (571, 215346, 20, 'Austin Helgeson', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (572, 215346, 45, 'Trevor J Switkowski', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (573, 215346, 31, 'Chris   Hibbert', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (574, 215346, 8, 'Lukas F Weber', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (575, 215346, 33, 'James Kennedy', 'Tyrannosaurs', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (576, 215346, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (577, 215346, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (578, 215346, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (579, 215346, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (580, 215346, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (581, 215346, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (582, 215346, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (583, 215346, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (584, 215346, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (585, 215346, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (586, 215346, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (587, 215346, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (588, 215346, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (589, 215346, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (590, 218204, 0, 'Derek S Batoyon', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (591, 218204, 21, 'Michael D Hutton', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (592, 218204, 41, 'Brennan M Bennardo', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (593, 218204, 13, 'Razzak G Jallow', 'Team America', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (594, 218204, 10, 'Mrityunjoy Dhar', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (595, 218204, 18, 'John W Kiely', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (596, 218204, 0, 'Bryan F Fulgado', 'Team America', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (597, 218204, 40, 'Michael P Kurnellas', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (598, 218204, 42, 'Kurt R Hazlitt', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (599, 218204, 81, 'Michael T Nyland', 'Team America', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (600, 218204, 0, 'Man Him Andrew Ho', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (601, 218204, 33, 'Christian Plante', 'Team America', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (602, 218204, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (603, 218204, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (604, 218204, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (605, 218204, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (606, 218204, 22, 'SHIRAZ F KHAN', 'Beerbears on Ice', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (607, 218204, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (608, 218204, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (609, 218204, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (610, 218204, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (611, 218204, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (612, 218204, 32, 'Jonathan Zing', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (613, 223792, 1, 'Mohsin S Barra', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (614, 223792, 91, 'Benjamin E Pearson', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (615, 223792, 11, 'Francois Bedard', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (616, 223792, 13, 'Timothy D Pettitt', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (617, 223792, 31, 'Breanne L Doyle', 'Money Shots II', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (618, 223792, 33, 'Ed Sanchez', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (619, 223792, 42, 'John Grass', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (620, 223792, 81, 'Lisa A Scotch', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (621, 223792, 3, 'Jody Greenberg', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (622, 223792, 8, 'Gordon L Shyy', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (623, 223792, 35, 'John F Hauser', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (624, 223792, 92, 'Derek L St Louis', 'Money Shots II', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (625, 223792, 0, 'Patrick W Heil', 'Money Shots II', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (626, 223792, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (627, 223792, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (628, 223792, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (629, 223792, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (630, 223792, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (631, 223792, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (632, 223792, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (633, 223792, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (634, 223792, 14, 'Matthew M Miller', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (635, 223792, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (636, 223792, 15, 'John F New', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (637, 223792, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (638, 219278, 0, 'Joey O Andolina', 'Beasts of Bourbon', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (639, 219278, 29, 'Matthew J Gault', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (640, 219278, 86, 'Jordan R Bean', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (641, 219278, 85, 'Jeffrey R Gisin', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (642, 219278, 82, 'Lukas L Bell', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (643, 219278, 16, 'Julian Lucas', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (644, 219278, 81, 'Ryan Cheung', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (645, 219278, 40, 'Jason Mah', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (646, 219278, 92, 'Blaize A Dunn', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (647, 219278, 80, 'William A Vogel', 'Beasts of Bourbon', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (648, 219278, 88, 'Aaron Farrell', 'Beasts of Bourbon', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (649, 219278, 39, 'Michael R Beam', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (650, 219278, 47, 'Ryan S Newberry', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (651, 219278, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (652, 219278, 92, 'James Pollaro', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (653, 219278, 94, 'Jeffrey   Ho', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (654, 219278, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (655, 219278, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (656, 219278, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (657, 219278, 4, 'Justin M Kingrey', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (658, 219278, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (659, 219278, 21, 'Timothy Lynn', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (660, 219278, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (661, 219278, 49, 'Alan J Menezes', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (662, 243035, 29, 'Kenneth R Douglas', 'Beerbears on Ice', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (663, 243035, 28, 'Andreas Schmid', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (664, 243035, 20, 'William A Kessler', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (665, 243035, 18, 'Mikhail Smirnov', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (666, 243035, 55, 'Kiel R Mariant', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (667, 243035, 6, 'Steven R Surrette', 'Beerbears on Ice', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (668, 243035, 13, 'David-Kim T Nguyen', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (669, 243035, 86, 'Paul C Wong', 'Beerbears on Ice', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (670, 243035, 69, 'Ian Rohwer', 'Beerbears on Ice', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (671, 243035, 5, 'Calvin J Borneman', 'Blade Runners', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (672, 243035, 19, 'Ron   Koronkowski', 'Blade Runners', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (673, 243035, 9, 'Brett R Dippert', 'Blade Runners', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (674, 243035, 31, 'Phillip E Linarte', 'Blade Runners', 'G');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (675, 243035, 17, 'Steve A Dippert', 'Blade Runners', 'C');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (676, 243035, 48, 'Kamila Nowicki', 'Blade Runners', 'S');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (677, 243035, 11, 'Reid O Eggebraaten', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (678, 243035, 42, 'Steven M Pierre', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (679, 243035, 79, 'Jared M Elson', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (680, 243035, 18, 'David L Formenti', 'Blade Runners', 'A');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (681, 243035, 91, 'Sean M Wachob', 'Blade Runners', '');
INSERT INTO players (PlayerId, GameId, Number, Name, Team, Pos) VALUES (682, 243035, 14, 'Joseph G Hanna', 'Blade Runners', '');
